/**
 * Deterministic synthetic demo world: "Northstar Labs".
 *
 * All data is newly authored fiction generated by owned seeded generators.
 * The same seed input reproduces identical fixtures in any environment.
 */
import { computeSlaState } from "@recruiterpal/domain";
import type { RecruiterPalDb } from "../client.js";
import * as s from "../schema.js";

// ---------------------------------------------------------------------------
// Seeded PRNG (mulberry32) — deterministic across platforms/runs.
// ---------------------------------------------------------------------------

export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(rng: () => number, arr: readonly T[]): T {
  const i = Math.floor(rng() * arr.length);
  return arr[i]!;
}

function pickInt(rng: () => number, minInclusive: number, maxInclusive: number): number {
  return minInclusive + Math.floor(rng() * (maxInclusive - minInclusive + 1));
}

const FIRST_NAMES = [
  "Ava", "Noah", "Mia", "Liam", "Zoe", "Ethan", "Ivy", "Owen", "Nina", "Felix",
  "Ruth", "Jonas", "Clara", "Marcus", "Priya", "Diego", "Hana", "Tomas", "Leila", "Victor",
  "Sofia", "Mateo", "Amara", "Kenji", "Freya", "Omar", "Ingrid", "Ravi", "Elena", "Sam",
  "Talia", "Bruno", "Yuki", "Carla", "Dmitri", "Nadia", "Peter", "Quinn", "Rosa", "Stefan",
] as const;

const LAST_NAMES = [
  "Alvarez", "Bergström", "Chen", "Dubois", "Eriksen", "Fontaine", "Garcia", "Haddad",
  "Ivanova", "Jensen", "Kowalski", "Laurent", "Moreau", "Novak", "Okafor", "Petrov",
  "Quintero", "Rossi", "Silva", "Tanaka", "Ueda", "Vargas", "Weber", "Xu", "Young",
  "Zimmerman", "Adeyemi", "Bianchi", "Castillo", "Duarte",
] as const;

const HEADLINES = [
  "Senior backend engineer focused on distributed systems",
  "ML engineer with production recommendation systems experience",
  "Full-stack engineer, fintech background",
  "Data scientist specializing in experimentation",
  "Platform engineer, Kubernetes and developer tooling",
  "Staff engineer with high-scale API experience",
  "Product-minded frontend engineer",
  "Data engineer, streaming pipelines",
] as const;

const SOURCES = ["REFERRAL", "LINKEDIN", "INBOUND", "AGENCY", "CAREERS_PAGE"] as const;
const STAGES = [
  "APPLIED",
  "RECRUITER_REVIEW",
  "RECRUITER_SCREEN",
  "HM_REVIEW",
  "TECHNICAL_ASSESSMENT",
  "INTERVIEW_LOOP",
  "DECISION",
  "OFFER",
] as const;
const REQUIRED_STAGES = ["RECRUITER_REVIEW", "RECRUITER_SCREEN", "INTERVIEW_LOOP"] as const;

interface SeedUser {
  id: string;
  name: string;
  email: string;
  role: string;
}

export interface DemoWorldIds {
  organizationId: string;
  securityOrgId: string;
  recruiterLeadId: string;
  recruiters: SeedUser[];
  interviewers: SeedUser[];
  jobs: { id: string; title: string; protocolVersionId: string; status: string }[];
  sofiaApplicationId: string | null;
}

export interface SeedOptions {
  /** Master seed; identical values reproduce identical worlds. */
  seed?: number;
  now?: Date;
  candidateCount?: number;
}

/**
 * Generate the full Northstar Labs world inside one transaction (service role,
 * seeding is an explicit backend path).
 */
export async function seedDemoWorld(
  db: RecruiterPalDb,
  options: SeedOptions = {},
): Promise<DemoWorldIds> {
  const rng = mulberry32(options.seed ?? 1337);
  const now = options.now ?? new Date();
  const day = 24 * 60 * 60 * 1000;
  const daysAgo = (n: number) => new Date(now.getTime() - n * day);

  return db.transaction(async (tx) => {
    // ---- Organizations -----------------------------------------------------
    const [northstar] = await tx
      .insert(s.organizations)
      .values({ name: "Northstar Labs", slug: "northstar-labs" })
      .returning({ id: s.organizations.id });
    const [securityOrg] = await tx
      .insert(s.organizations)
      .values({ name: "Meridian Compliance Group", slug: "meridian-compliance" })
      .returning({ id: s.organizations.id });
    const orgId = northstar!.id;
    const secOrgId = securityOrg!.id;

    // ---- People ------------------------------------------------------------
    const passwordNote = "demo-only accounts";
    void passwordNote;
    async function insertUser(name: string, email: string, role: string, org: string): Promise<SeedUser> {
      const [u] = await tx
        .insert(s.users)
        .values({ name, email, emailVerified: true })
        .returning({ id: s.users.id });
      await tx.insert(s.memberships).values({ organizationId: org, userId: u!.id, role });
      return { id: u!.id, name, email, role };
    }

    const lead = await insertUser("Jordan Reyes", "jordan.reyes@northstar-labs.example", "admin", orgId);
    const recruiters: SeedUser[] = [];
    const recruiterNames = [
      ["Casey Lin", "casey.lin@northstar-labs.example"],
      ["Morgan Diaz", "morgan.diaz@northstar-labs.example"],
      ["Taylor Brooks", "taylor.brooks@northstar-labs.example"],
    ] as const;
    for (const [name, email] of recruiterNames) {
      recruiters.push(await insertUser(name, email, "recruiter", orgId));
    }
    const interviewerNames = [
      ["Dr. Elena Vasquez", "elena.vasquez@northstar-labs.example", "hiring_manager"],
      ["Sam Whitfield", "sam.whitfield@northstar-labs.example", "hiring_manager"],
      ["Priya Raman", "priya.raman@northstar-labs.example", "interviewer"],
      ["Kenji Mori", "kenji.mori@northstar-labs.example", "interviewer"],
      ["Freya Lindqvist", "freya.lindqvist@northstar-labs.example", "interviewer"],
      ["Omar Haddad", "omar.haddad@northstar-labs.example", "interviewer"],
    ] as const;
    const interviewers: SeedUser[] = [];
    for (const [name, email, role] of interviewerNames) {
      interviewers.push(await insertUser(name, email, role, orgId));
    }

    // Security-test tenant: one isolated user, no shared rows.
    await insertUser("Alex Meridian", "alex.meridian@meridian-compliance.example", "owner", secOrgId);

    const allPanelists = [...interviewers.filter((i) => i.role === "interviewer")];

    // ---- Competencies -------------------------------------------------------
    const competencyNames = [
      "Production Engineering Craft",
      "System Design",
      "Data Modeling & Analysis",
      "Communication & Collaboration",
      "Ownership & Delivery",
      "Problem Solving Under Ambiguity",
      "Technical Leadership",
    ];
    const compIds: Record<string, string> = {};
    for (const name of competencyNames) {
      const [c] = await tx
        .insert(s.competencies)
        .values({
          organizationId: orgId,
          name,
          description: `Assessed against anchored rubric for ${name}.`,
        })
        .returning({ id: s.competencies.id });
      compIds[name] = c!.id;
    }

    // ---- Jobs + protocols ---------------------------------------------------
    const jobSpecs = [
      { title: "Senior ML Engineer", department: "Applied Science", openDaysAgo: 75, status: "OPEN", drift: false },
      { title: "Staff Backend Engineer", department: "Platform", openDaysAgo: 60, status: "OPEN", drift: false },
      { title: "Data Scientist", department: "Analytics", openDaysAgo: 55, status: "OPEN", drift: true },
      { title: "Senior Product Engineer", department: "Product", openDaysAgo: 48, status: "OPEN", drift: false },
      { title: "Data Engineer", department: "Data Platform", openDaysAgo: 40, status: "OPEN", drift: false },
      { title: "Security Engineer", department: "Infrastructure", openDaysAgo: 33, status: "ON_HOLD", drift: false },
      { title: "Engineering Manager", department: "Platform", openDaysAgo: 28, status: "OPEN", drift: false },
      { title: "Quantitative Researcher", department: "Applied Science", openDaysAgo: 20, status: "OPEN", drift: false },
    ];

    const jobsOut: DemoWorldIds["jobs"] = [];
    let sofiaAppIdGlobal: string | null = null;

    function stagesFor(spec: (typeof jobSpecs)[number]) {
      return STAGES.map((name) => ({ name, required: REQUIRED_STAGES.includes(name as never) || name === "OFFER" }));
    }

    for (let ji = 0; ji < jobSpecs.length; ji++) {
      const spec = jobSpecs[ji]!;
      const owner = recruiters[ji % recruiters.length]!;
      const hm = interviewers.find((i) => i.role === "hiring_manager")!;
      const [job] = await tx
        .insert(s.jobs)
        .values({
          organizationId: orgId,
          title: spec.title,
          department: spec.department,
          locationMode: ji % 3 === 0 ? "HYBRID" : "REMOTE",
          employmentType: "FULL_TIME",
          status: spec.status,
          ownerRecruiterId: owner.id,
          hiringManagerId: hm.id,
          openedAt: spec.status === "OPEN" ? daysAgo(spec.openDaysAgo) : null,
          targetFillDate: new Date(now.getTime() + pickInt(rng, 21, 70) * day),
        })
        .returning({ id: s.jobs.id });

      const [protocol] = await tx
        .insert(s.hiringProtocols)
        .values({ organizationId: orgId, jobId: job!.id })
        .returning({ id: s.hiringProtocols.id });

      const stageList = stagesFor(spec);
      const [v1] = await tx
        .insert(s.hiringProtocolVersions)
        .values({
          organizationId: orgId,
          protocolId: protocol!.id,
          versionLabel: "hp-1.0",
          status: "APPROVED",
          rolePurpose: `Hire an exceptional ${spec.title} for ${spec.department}.`,
          criticalTasks: [`Own ${spec.title.toLowerCase()} deliverables end to end`],
          mustHaveRequirements:
            spec.title === "Data Scientist"
              ? ["5+ years applied statistics", "Experimentation design"]
              : ["Strong production engineering track record", "Clear written communication"],
          trainableRequirements: ["Specific domain tooling"],
          stages: stageList,
          approvedByUserId: lead.id,
          approvedAt: daysAgo(spec.openDaysAgo + 2),
          effectiveAt: daysAgo(spec.openDaysAgo),
        })
        .returning({ id: s.hiringProtocolVersions.id });

      let activeVersionId = v1!.id;

      if (spec.drift) {
        // Requirement drift scenario: v1.1 changed one must-have criterion 8 days ago.
        const [v2] = await tx
          .insert(s.hiringProtocolVersions)
          .values({
            organizationId: orgId,
            protocolId: protocol!.id,
            versionLabel: "hp-1.1",
            status: "APPROVED",
            rolePurpose: `Hire an exceptional ${spec.title} for ${spec.department}.`,
            criticalTasks: [`Own ${spec.title.toLowerCase()} deliverables end to end`],
            mustHaveRequirements: ["5+ years applied statistics", "Causal inference experience (added)"],
            trainableRequirements: ["Specific domain tooling"],
            stages: stageList,
            approvedByUserId: lead.id,
            approvedAt: daysAgo(8),
            effectiveAt: daysAgo(8),
          })
          .returning({ id: s.hiringProtocolVersions.id });
        activeVersionId = v2!.id;
        await tx.insert(s.exceptions).values({
          organizationId: orgId,
          deduplicationKey: `${orgId}:${job!.id}:protocol_drift:v1`,
          type: "protocol_drift",
          severity: "LOW",
          jobId: job!.id,
          title: `${spec.title}: requirements changed 8 days ago`,
          detail:
            "One must-have criterion was added in hp-1.1. Screen-stage conversion dropped after the change; association observed, causality unproven.",
          status: "OPEN",
        });
      }

      await tx.update(s.jobs).set({ activeProtocolVersionId: activeVersionId }).where(eqJob(job!.id));

      // Protocol competencies
      const requiredComps = competencyNames.slice(0, 5);
      for (const name of requiredComps) {
        await tx.insert(s.protocolCompetencies).values({
          organizationId: orgId,
          protocolVersionId: activeVersionId,
          competencyId: compIds[name]!,
          requiredLevel: pickInt(rng, 3, 4),
          evidenceSource: "INTERVIEW_SCORECARD",
          isRequired: true,
        });
      }

      // Scorecard template
      const [tmpl] = await tx
        .insert(s.scorecardTemplates)
        .values({
          organizationId: orgId,
          protocolVersionId: activeVersionId,
          name: `${spec.title} — panel scorecard`,
          rubricAnchors: {
            "1": "no credible evidence demonstrated",
            "3": "demonstrates competence with guidance",
            "5": "demonstrates independent mastery",
          },
          competencyIds: requiredComps.map((n) => compIds[n]!),
        })
        .returning({ id: s.scorecardTemplates.id });
      const templateId = tmpl!.id;

      jobsOut.push({ id: job!.id, title: spec.title, protocolVersionId: activeVersionId, status: spec.status });

      // ---- Applications ----------------------------------------------------
      const targetApps = spec.status === "OPEN" ? pickInt(rng, 14, 24) : 6;
      let sofiaApplicationId: string | null = null;

      for (let ai = 0; ai < targetApps; ai++) {
        const firstIdx = Math.floor(rng() * FIRST_NAMES.length);
        const lastIdx = Math.floor(rng() * LAST_NAMES.length);
        const firstName =
          spec.title === "Senior ML Engineer" && ai === 0 ? "Sofia" : FIRST_NAMES[firstIdx]!;
        const lastName = spec.title === "Senior ML Engineer" && ai === 0 ? "Martinez" : LAST_NAMES[lastIdx]!;

        const [candidate] = await tx
          .insert(s.candidates)
          .values({
            organizationId: orgId,
            firstName,
            lastName,
            email: `${firstName.toLowerCase()}.${lastName.toLowerCase().replace(/[^a-z]/g, "")}${ai}@candidates.example`,
            headline: pick(rng, HEADLINES),
            source: pick(rng, SOURCES),
          })
          .returning({ id: s.candidates.id });

        // Stage distribution weighted toward early funnel; last few in final stages.
        const isSofia = spec.title === "Senior ML Engineer" && ai === 0;
        const deepStage = isSofia || (ai >= targetApps - 3 && spec.status === "OPEN");
        const stage = deepStage
          ? isSofia
            ? "INTERVIEW_LOOP"
            : pick(rng, ["INTERVIEW_LOOP", "DECISION", "OFFER"])
          : pick(rng, STAGES.slice(0, 5));
        const appliedDays = pickInt(rng, 10, Math.min(spec.openDaysAgo, 85));
        const [application] = await tx
          .insert(s.applications)
          .values({
            organizationId: orgId,
            jobId: job!.id,
            candidateId: candidate!.id,
            status: "ACTIVE",
            currentStage: stage,
            source: pick(rng, SOURCES),
            ownerRecruiterId: owner.id,
            protocolVersionId: activeVersionId,
            appliedAt: daysAgo(appliedDays),
            lastActivityAt: daysAgo(pickInt(rng, 0, 9)),
            nextExpectedActionAt: new Date(now.getTime() + pickInt(rng, -3, 10) * day),
          })
          .returning({ id: s.applications.id });

        // Stage history
        const stagePath = STAGES.slice(0, STAGES.indexOf(stage as never) + 1);
        let prevStage: string | null = null;
        let cursorDays = appliedDays;
        for (const st of stagePath) {
          await tx.insert(s.applicationStageEvents).values({
            organizationId: orgId,
            applicationId: application!.id,
            fromStage: prevStage,
            toStage: st,
            reason: prevStage ? "advanced by recruiter" : "initial application",
            actorType: "HUMAN",
            actorUserId: owner.id,
            protocolVersionId: activeVersionId,
            occurredAt: daysAgo(cursorDays),
          });
          prevStage = st;
          cursorDays = Math.max(0, cursorDays - pickInt(rng, 2, 8));
        }

        // ---- Interviews / scorecards --------------------------------------
        const needsInterviews = ["TECHNICAL_ASSESSMENT", "INTERVIEW_LOOP", "DECISION", "OFFER"].includes(stage);
        if (needsInterviews) {
          const interviewCount = stage === "DECISION" || stage === "OFFER" ? 3 : pickInt(rng, 1, 2);
          for (let ii = 0; ii < interviewCount; ii++) {
            // Golden G1: Sofia's first loop interview is deterministically
            // completed with a two-rater panel and conflicting submissions.
            const isSofiaFirst = spec.title === "Senior ML Engineer" && ai === 0 && ii === 0;
            const completed = isSofiaFirst ? true : rng() > 0.35;
            const scheduledStart = completed
              ? daysAgo(pickInt(rng, 3, 15))
              : new Date(now.getTime() + pickInt(rng, 1, 12) * day);
            let panel = [pick(rng, allPanelists), pick(rng, allPanelists)].filter(
              (p, idx, arr) => arr.findIndex((q) => q.id === p.id) === idx,
            );
            if (isSofiaFirst && panel.length < 2) panel = [...panel, allPanelists[0]!];
            const [interview] = await tx
              .insert(s.interviews)
              .values({
                organizationId: orgId,
                applicationId: application!.id,
                jobId: job!.id,
                label: `${spec.title} interview ${ii + 1}`,
                status: completed ? "COMPLETED" : "SCHEDULED",
                scheduledStartAt: scheduledStart,
                scheduledEndAt: new Date(scheduledStart.getTime() + 60 * 60 * 1000),
                completedAt: completed ? new Date(scheduledStart.getTime() + 3600_000) : null,
                requiresScorecardsFrom: panel.length,
                protocolVersionId: activeVersionId,
              })
              .returning({ id: s.interviews.id });

            for (const p of panel) {
              await tx.insert(s.interviewParticipants).values({
                interviewId: interview!.id,
                userId: p.id,
                organizationId: orgId,
                role: "INTERVIEWER",
                required: true,
              });
            }

            if (completed) {
              // Golden G2: one specific completed interview is missing a scorecard past SLA.
              const missingScorecardScenario = spec.title === "Staff Backend Engineer" && ai === 0 && ii === 0;
              for (let pi = 0; pi < panel.length; pi++) {
                const rater = panel[pi]!;
                const skip = missingScorecardScenario && pi === 0;
                const openedAt = new Date(scheduledStart.getTime());
                const [sc] = await tx
                  .insert(s.scorecards)
                  .values({
                    organizationId: orgId,
                    interviewId: interview!.id,
                    applicationId: application!.id,
                    templateId: templateId!,
                    raterUserId: rater.id,
                    protocolVersionId: activeVersionId,
                    status: skip ? "OPEN" : "SUBMITTED",
                    openedAt,
                    submittedAt: skip ? null : new Date(openedAt.getTime() + 2 * day),
                  })
                  .returning({ id: s.scorecards.id });

                if (skip) {
                  await tx.insert(s.applicationObligations).values({
                    organizationId: orgId,
                    applicationId: application!.id,
                    interviewId: interview!.id,
                    obligationType: "SCORECARD_SUBMISSION",
                    responsibleUserId: rater.id,
                    dueAt: new Date(openedAt.getTime() + 48 * 3600_000),
                    state: "ESCALATED",
                    workflowRef: "wf_scorecard_chase:seeded",
                  });
                  await tx.insert(s.exceptions).values({
                    organizationId: orgId,
                    deduplicationKey: `${orgId}:${application!.id}:overdue_scorecard:${rater.id}:v1`,
                    type: "overdue_scorecard",
                    severity: "HIGH",
                    jobId: job!.id,
                    applicationId: application!.id,
                    interviewId: interview!.id,
                    title: `Scorecard overdue from ${rater.name}`,
                    detail: `Required scorecard for ${firstName} ${lastName} (${spec.title}) passed the 48h SLA. Reminder sent by workflow; escalation threshold reached.`,
                    status: "AUTO_RESOLVING",
                  });
                } else {
                  // Ratings: golden G1 conflict embedded on Sofia's loop.
                  for (const cname of requiredComps) {
                    let rating = pickInt(rng, 2, 5);
                    if (isSofiaFirst && cname === "Technical Leadership") {
                      rating = pi === 0 ? 5 : 3; // crosses the level-3 advancement threshold
                    }
                    await tx
                      .insert(s.scorecardRatings)
                      .values({
                        scorecardId: sc!.id,
                        competencyId: compIds[cname]!,
                        organizationId: orgId,
                        rating,
                        evidenceNote: `Observed concrete examples during ${spec.title} interview.`,
                        rubricAnchor:
                          rating >= 4
                            ? "independent production implementation"
                            : "competent with guidance",
                      })
                      .onConflictDoNothing();
                  }
                }
              }
            }
          }
        }

        if (spec.title === "Senior ML Engineer" && ai === 0) {
          sofiaApplicationId = application!.id;
        }
      }

      if (sofiaApplicationId) {
        await tx
          .update(s.applications)
          .set({ currentStage: "DECISION", candidateDeadlineAt: new Date(now.getTime() + day), deadlineVerified: "UNVERIFIED" })
          .where(eqApp(sofiaApplicationId));
        await tx.insert(s.exceptions).values({
          organizationId: orgId,
          deduplicationKey: `${orgId}:${sofiaApplicationId}:candidate_deadline_risk:v1`,
          type: "candidate_deadline_risk",
          severity: "CRITICAL",
          jobId: job!.id,
          applicationId: sofiaApplicationId,
          title: "Sofia Martinez: competing offer deadline within 24h",
          detail:
            "Candidate stated a competing offer deadline in inbound email (extracted fact, UNVERIFIED). Evidence complete except one material scorecard conflict requiring human review. No automated advancement will occur.",
          deadlineAt: new Date(now.getTime() + day),
          status: "WAITING_HUMAN",
        });
        sofiaAppIdGlobal = sofiaApplicationId;
      }
    }

    return {
      organizationId: orgId,
      securityOrgId: secOrgId,
      recruiterLeadId: lead.id,
      recruiters,
      interviewers,
      jobs: jobsOut,
      sofiaApplicationId: sofiaAppIdGlobal,
    };
  });
}

// Small helpers kept local to avoid importing drizzle operators everywhere.
import { eq } from "drizzle-orm";
function eqJob(id: string) {
  return eq(s.jobs.id, id);
}
function eqApp(id: string) {
  return eq(s.applications.id, id);
}
